import '@/styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Head from 'next/head'
import Layout from '@/components/Layout'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Revive bad photos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header/> */}
      <Layout>
        <Component {...pageProps} />
      </Layout>
      {/* <Footer/> */}
    </>
  )
}
