import '@/styles/globals.css'
import Head from 'next/head'
import Layout from '@/components/Layout'

export default function App({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>Revive Old Photos with AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/iconico.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
