import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import original from '../public/badImage.png'
import revived from '../public/goodImage.png'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Revive bad photos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;400;700&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.info}>
          <h1>Making old photos new <br></br> again through AI</h1>
          <p>Bring your faded and unclear face photos back to 
            life with the help of AI. Keep those cherished 
            memories alive for free. Start restoring your photos now.
          </p>
          <Link href='/revive'><button>Restore photo</button></Link>
        </div>
        <div className={styles.imagesection}>
          <div>
            <p>Original Photo</p>
            <Image src={original} width='400' height='400' alt='original image' />
          </div>
          <div>
            <p>Revived Photo</p>
            <Image src={revived} width='400' height='400' alt='original image' />
          </div>
        </div>
      </main>
    </>
  )
}
